In [1]:
import numpy as np

In [2]:
a = np.array([6, 7, 8, 9])
a

array([6, 7, 8, 9])

In [3]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
# 2 to 8 (8 exclusive)
np.arange(2, 8)

array([2, 3, 4, 5, 6, 7])

In [7]:
# start, finish, step
np.arange(0, 1, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [8]:
a = np.arange(6, 10)
a

array([6, 7, 8, 9])

In [9]:
# slicing
b = a[2:]
b

array([8, 9])

In [10]:
# start:end:step slicing (works on lists in standard python)
b = a[1::2]
b

array([7, 9])

In [18]:
a = np.arange(10)
b = a[::1]
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
# reverse from above
b = a[::-1]
b

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [24]:
a = np.arange(10)
half = a[:5]
half = a.copy()
half[0] += 50
print(a[0])

0
