In [2]:
import numpy as np
import time

def practice(cols):
    rows = np.random.randint(3, 7)
    A = np.random.randint(-3,4,(rows, cols))
    b = np.random.randint(-3,4,cols).reshape(-1,1)
    print("A = ")
    print(A)
    print()
    print("b = ")
    print(b)
    print()
    M = np.dot(A,b).astype(object)
    pos = np.random.randint(0,rows)
    expected, M[pos,0] = M[pos,0], "x"
    print("np.dot(A,b) = ")
    print(M)    
    print()
    answer = int(input("What is 'x'?  "))
    print()
    if answer == expected:
        print("Good job!")
        return True
    else:
        print("\nActually, it is ", expected)
        print("Calculation:", " + ".join(f"({x}*{y})" for x,y in zip(A[pos].reshape(-1), b.reshape(-1))))
        time.sleep(2)
        return False

goal = 3
correct = 0
while correct < goal:
    print("="*40)
    print(f"Get {goal-correct} in a row correct to finish!")
    print("="*40)
    print()
    if practice(correct+2):
        correct += 1
    else:
        correct = 0
    print()
        
print(f"Nice, you got {goal} in a row correct!")

Get 3 in a row correct to finish!

A = 
[[ 1  1]
 [ 0  3]
 [-3  0]
 [-2 -3]
 [ 0  3]]

b = 
[[-2]
 [ 1]]

np.dot(A,b) = 
[['x']
 [3]
 [6]
 [1]
 [3]]

What is 'x'?  3


Actually, it is  -1
Calculation: (1*-2) + (1*1)

Get 3 in a row correct to finish!

A = 
[[ 2 -3]
 [ 3  3]
 [-1  2]
 [-3  3]]

b = 
[[1]
 [3]]

np.dot(A,b) = 
[[-7]
 [12]
 [5]
 ['x']]

What is 'x'?  6

Good job!

Get 2 in a row correct to finish!

A = 
[[ 0  3  2]
 [-1  1  3]
 [ 1 -3  0]]

b = 
[[2]
 [3]
 [1]]

np.dot(A,b) = 
[[11]
 ['x']
 [-7]]

What is 'x'?  4

Good job!

Get 1 in a row correct to finish!

A = 
[[-3  1  3  0]
 [ 1 -3  0  2]
 [-3  0  3  1]
 [-1  2  2 -1]]

b = 
[[-3]
 [ 2]
 [ 3]
 [ 2]]

np.dot(A,b) = 
[['x']
 [-5]
 [20]
 [11]]

What is 'x'?  20

Good job!

Nice, you got 3 in a row correct!
