In [ ]:
import numpy as np
import time

def practice():
    size = np.random.randint(1,5)
    a = np.random.randint(-3,4,size).reshape(-1,1)
    b = np.random.randint(-3,4,size).reshape(-1,1)
    print("a = ")
    print(a)
    print()
    print("b = ")
    print(b)
    print()
    answer = int(input("What is np.dot(a.T,b), as a scalar?  "))
    print()
    expected = np.dot(a.T, b)[0][0]
    if answer == expected:
        print("Good job!")
        return True
    else:
        print("\nActually, it is ", expected)
        print("Calculation:", " + ".join(f"({x}*{y})" for x,y in zip(a.reshape(-1), b.reshape(-1))))
        time.sleep(2)
        return False

goal = 5
correct = 0
while correct < goal:
    print("="*40)
    print(f"Get {goal-correct} in a row correct to finish!")
    print("="*40)
    print()
    if practice():
        correct += 1
    else:
        correct = 0
    print()
        
print(f"Nice, you got {goal} in a row correct!")

Get 5 in a row correct to finish!

a = 
[[-3]
 [-1]
 [-3]
 [ 2]]

b = 
[[2]
 [2]
 [0]
 [2]]

What is np.dot(a.T,b), as a scalar?  10


Actually, it is  -4
Calculation: (-3*2) + (-1*2) + (-3*0) + (2*2)

Get 5 in a row correct to finish!

a = 
[[ 0]
 [ 1]
 [-3]
 [ 2]]

b = 
[[ 3]
 [-1]
 [-3]
 [ 3]]

What is np.dot(a.T,b), as a scalar?  14

Good job!

Get 4 in a row correct to finish!

a = 
[[2]
 [2]
 [3]
 [3]]

b = 
[[ 1]
 [-1]
 [ 3]
 [-2]]

What is np.dot(a.T,b), as a scalar?  3

Good job!

Get 3 in a row correct to finish!

a = 
[[1]
 [1]]

b = 
[[-2]
 [ 1]]

What is np.dot(a.T,b), as a scalar?  -1

Good job!

Get 2 in a row correct to finish!

a = 
[[-1]
 [-3]
 [-1]]

b = 
[[-1]
 [-2]
 [-1]]

What is np.dot(a.T,b), as a scalar?  8

Good job!

Get 1 in a row correct to finish!

a = 
[[-2]
 [ 2]
 [ 1]
 [-2]]

b = 
[[ 1]
 [ 3]
 [ 0]
 [-2]]

What is np.dot(a.T,b), as a scalar?  0


Actually, it is  8
Calculation: (-2*1) + (2*3) + (1*0) + (-2*-2)

Get 5 in a row correct to finish!

a = 
[[