In [3]:
import numpy as np

u = np.array([[-0.21483724,  0.88723069,  0.40824829],
              [-0.52058739,  0.24964395, -0.81649658],
              [-0.82633754, -0.38794278,  0.40824829]])
s = np.array([16.84810335261421, 1.06836951455471, 0])
vt = np.array([[-0.47967118, -0.57236779, -0.66506441],
               [-0.77669099, -0.07568647,  0.62531805],
               [-0.40824829,  0.81649658, -0.40824829]])

In [6]:
A = (u*s)@vt # option 1
A = (u*s).dot(vt) # option 2
np.round(A, 2)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [7]:
A = np.array([[4, 1, 7],
              [1, 4, 3],
              [7, 3, 4]])

v1 = np.array([0.68777769, 0.4381872, 0.69928217]).reshape(-1,1)
v2 = np.array([-0.1017017, -0.77186858, 0.29665168]).reshape(-1,1)
v3 = np.array([0.6627402, 0.20526185, -0.72016873]).reshape(-1,1)
v4 = np.array([0.89036881, -0.78460023, 0.30786775]).reshape(-1,1)

A.dot(v1) / v1
# v1 is not an eigenvector

array([[11.75419509],
       [10.35715557],
       [12.76471   ]])

In [8]:
A.dot(v2) / v2

array([[-8.82862705],
       [ 2.9787726 ],
       [-6.2056312 ]])

In [9]:
A.dot(v3) / v3
# v3 is an eigenvector with eigenvalue 3.29685518

array([[-3.29685518],
       [-3.29685516],
       [-3.29685521]])

In [1]:
import numpy as np
import pandas as pd

rows = [['M. Dupé', 1, 25, 'Right', 8.0, 900.0],
       ['N. Fernández', 26, 18, 'Right', 1.0, 450.0],
       ['P. Kalambayi', 30, 18, 'Right', 1.0, 130.0],
       ['P. McNair', 17, 23, 'Right', 22.0, 2300.0],
       ['G. Bojanich', 23, 33, 'Right', 6.0, 425.0],
       ['A. Kofler', 31, 31, 'Right', 3.0, 325.0],
       ['N. Lavanchy', 14, 24, 'Right', 3.0, 600.0],
       ['O. Al Khalaf', 8, 21, 'Right', 3.0, 240.0],
       ['J. Sills', 21, 31, 'Right', 7.0, 600.0],
       ['B. Fox', 12, 20, 'Right', 1.0, 230.0],
       ['S. Smith', 9, 20, 'Left', 4.0, 450.0],
       ['E. Ocansey', 28, 20, 'Left', 5.0, 1600.0],
       ['F. Kostić', 10, 25, 'Left', 16.0, 10500.0],
       ['M. Ullmann', 13, 22, 'Left', 3.0, 1000.0],
       ['R. Taylor', 9, 30, 'Left', 4.0, 625.0],
       ['N. Vikonis', 34, 34, 'Left', 7.0, 2700.0],
       ['J. Aguirre', 29, 21, 'Left', 1.0, 575.0],
       ['J. Konings', 25, 20, 'Left', 1.0, 500.0],
       ['J. Raitala', 22, 29, 'Left', 3.0, 700.0],
       ['A. Taylor', 3, 31, 'Left', 3.0, 425.0]]
df = pd.DataFrame.from_records(rows, columns=["Name", "JerseyNumber", "Age", "PreferredFoot", "Wage", "Value"])
df["PreferredFootInt"] = (df["PreferredFoot"] == "Right").astype(int)
df = df[["JerseyNumber", "Age", "Wage", "Value", "PreferredFootInt"]]
df

JerseyNumber  Age  Wage    Value  PreferredFootInt
0              1   25   8.0    900.0                 1
1             26   18   1.0    450.0                 1
2             30   18   1.0    130.0                 1
3             17   23  22.0   2300.0                 1
4             23   33   6.0    425.0                 1
5             31   31   3.0    325.0                 1
6             14   24   3.0    600.0                 1
7              8   21   3.0    240.0                 1
8             21   31   7.0    600.0                 1
9             12   20   1.0    230.0                 1
10             9   20   4.0    450.0                 0
11            28   20   5.0   1600.0                 0
12            10   25  16.0  10500.0                 0
13            13   22   3.0   1000.0                 0
14             9   30   4.0    625.0                 0
15            34   34   7.0   2700.0                 0
16            29   21   1.0    575.0                 0
17            25   20   1.0    500.0                 0
18            22   29   3.0    700.0                 0
19             3   31   3.0    425.0                 0

In [2]:
# How many principal components are necessary to capture at least 99% of the variance? 
# Run the following to find out (notice we only care about the absolute 
# values of the eigenvalues in s -- we can ignore the other return values with _):

_,s,_ = np.linalg.svd(df)
s = np.array(sorted(np.abs(s), reverse=True))
s.cumsum() / s.sum()
# 2 components, because 1 only gets us to 0.98439685, but two components together gets us to 0.99521466.

array([0.98439685, 0.99521466, 0.99836246, 0.999822  , 1.        ])